#!/bin/bash
set -e

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
readonly SCRIPT_DIR

main () {
  apt-get update
  install_nginx
  config_nginx
}

config_nginx () {
  ufw allow 'Nginx HTTP'
  ufw allow 'Nginx HTTPS'
}

install_nginx () {
  apt-get install -y nginx
}

main "$@"
